changelog:
  exclude:
    labels:
      - changelog:skip
  categories:
    - title: Added
      labels:
        - changelog:added
    - title: Changed
      labels:
        - changelog:changed
    - title: Deprecated
      labels:
        - changelog:deprecated
    - title: Removed
      labels:
        - changelog:removed
    - title: Fixed
      labels:
        - changelog:fixed
    - title: Security
      labels:
        - changelog:security
    - title: Other Unsorted Updates
      labels:
        - "*"
