[package]
name = "manta-simulation"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = "2.33.3"
indexmap = { version = "1.7.0", features = ["serde"] }
rand = "0.8.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
statrs = "0.15.0"

