// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

const backend = {
  main: {
    Service: {
      /**
       * AccountCreated
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      AccountCreated: () => {
        return window.backend.main.Service.AccountCreated();
      },
      /**
       * CreateAccount
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      CreateAccount: arg1 => {
        return window.backend.main.Service.CreateAccount(arg1);
      },
      /**
       * LoadRootSeed
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      LoadRootSeed: arg1 => {
        return window.backend.main.Service.LoadRootSeed(arg1);
      },
      /**
       * WindowHide
       * @returns {Promise<void>}
       */
      WindowHide: () => {
        return window.backend.main.Service.WindowHide();
      },
      /**
       * WindowShow
       * @returns {Promise<void>}
       */
      WindowShow: () => {
        return window.backend.main.Service.WindowShow();
      },
    },
  },
};
export default backend;
