// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

const backend = {
  "main": {
    "CommandService": {
      /**
       * WindowHide
       * @returns {Promise<void>} 
       */
      "WindowHide": () => {
        return window.backend.main.CommandService.WindowHide();
      },
    }
  }

};
export default backend;
