name: CI
on:
  pull_request:
  schedule:
    - cron: '0 0 * * */2'
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings -A unknown-lints
  RUST_BACKTRACE: full
jobs:
  test:
    name: Test (${{ matrix.os }} + ${{ matrix.channel }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        channel:
          - stable
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.channel }} --no-self-update && rustup default ${{ matrix.channel }}
      - run: cargo test --all-features --workspace --release
  lint:
    name: Lint (${{ matrix.os }} + ${{ matrix.channel }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        channel:
          - stable
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.channel }} && rustup default ${{ matrix.channel }} && rustup component add clippy
      - run: cargo install cargo-hack
      - run: cargo hack clippy --feature-powerset --workspace
      - run: cargo hack clippy --feature-powerset --workspace --bins
      - run: cargo hack clippy --feature-powerset --workspace --examples
      - run: cargo hack clippy --feature-powerset --workspace --tests
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update nightly && rustup default nightly && rustup component add rustfmt
    - run: cargo fmt --all -- --check
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly
      - run: RUSTDOCFLAGS="-D warnings --cfg doc_cfg" cargo +nightly doc --workspace --all-features --no-deps --document-private-items
  compile-bench:
    name: Compile Bench (${{ matrix.os }} + ${{ matrix.channel }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        channel:
          - stable
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.channel }} && rustup default ${{ matrix.channel }}
      - run: cargo bench --no-run --workspace --all-features
